{% set name = "setuptools-lint" %}
{% set version = "0.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e794e15c7c8dde970b618d9c7ad4588aeaea067f034ccb4ae8facc630b534199

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pylint
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - setuptools_lint

about:
  home: "https://github.com/johnnoone/setuptools-pylint"
  license: ZPL-2.1
  license_family: OTHER 
  license_file: # no license file in source distribution, issue here: https://github.com/johnnoone/setuptools-pylint/issues/15
  summary: "Setuptools command for pylint"
  doc_url: https://pypi.org/project/setuptools-lint/
  dev_url: https://github.com/johnnoone/setuptools-pylint

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
